name = "parking-spots"
main = "src/index.ts"
compatibility_date = "2026-04-15"

[[d1_databases]]
binding = "parking_spots_db"
database_name = "parking_spots_db"
database_id = "dbe5f0ff-f2b4-43b2-ba78-af4e771797fd"

[assets]
directory = "src/frontend/dist"

[triggers]
crons = ["*/3 * * * *"]
